<?php

/**
 * BasesfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $first_name
 * @property string $last_name
 * @property string $address
 * @property string $token
 * @property blob $foto
 * @property string $ubicacion
 * @property integer $puntuacion
 * @property sfGuardUser $User
 * 
 * @method integer            getUserId()     Returns the current record's "user_id" value
 * @method string             getFirstName()  Returns the current record's "first_name" value
 * @method string             getLastName()   Returns the current record's "last_name" value
 * @method string             getAddress()    Returns the current record's "address" value
 * @method string             getToken()      Returns the current record's "token" value
 * @method blob               getFoto()       Returns the current record's "foto" value
 * @method string             getUbicacion()  Returns the current record's "ubicacion" value
 * @method integer            getPuntuacion() Returns the current record's "puntuacion" value
 * @method sfGuardUser        getUser()       Returns the current record's "User" value
 * @method sfGuardUserProfile setUserId()     Sets the current record's "user_id" value
 * @method sfGuardUserProfile setFirstName()  Sets the current record's "first_name" value
 * @method sfGuardUserProfile setLastName()   Sets the current record's "last_name" value
 * @method sfGuardUserProfile setAddress()    Sets the current record's "address" value
 * @method sfGuardUserProfile setToken()      Sets the current record's "token" value
 * @method sfGuardUserProfile setFoto()       Sets the current record's "foto" value
 * @method sfGuardUserProfile setUbicacion()  Sets the current record's "ubicacion" value
 * @method sfGuardUserProfile setPuntuacion() Sets the current record's "puntuacion" value
 * @method sfGuardUserProfile setUser()       Sets the current record's "User" value
 * 
 * @package    scheedo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUserProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_profile');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('first_name', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('last_name', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('address', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('token', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('foto', 'blob', null, array(
             'type' => 'blob',
             ));
        $this->hasColumn('ubicacion', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('puntuacion', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}