<?php

/**
 * BaseEvento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property integer $user_id
 * @property integer $categoria_id
 * @property timestamp $fecha_inicio
 * @property timestamp $fecha_termino
 * @property string $lugar
 * @property blob $logo
 * @property string $telefono
 * @property string $mail
 * @property string $twitter
 * @property string $facebook
 * @property string $web1
 * @property integer $ranking
 * @property string $descripcion
 * @property boolean $is_active
 * @property sfGuardUser $User
 * @property Categoria $Categoria
 * @property Doctrine_Collection $Comentarios
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getNombre()        Returns the current record's "nombre" value
 * @method integer             getUserId()        Returns the current record's "user_id" value
 * @method integer             getCategoriaId()   Returns the current record's "categoria_id" value
 * @method timestamp           getFechaInicio()   Returns the current record's "fecha_inicio" value
 * @method timestamp           getFechaTermino()  Returns the current record's "fecha_termino" value
 * @method string              getLugar()         Returns the current record's "lugar" value
 * @method blob                getLogo()          Returns the current record's "logo" value
 * @method string              getTelefono()      Returns the current record's "telefono" value
 * @method string              getMail()          Returns the current record's "mail" value
 * @method string              getTwitter()       Returns the current record's "twitter" value
 * @method string              getFacebook()      Returns the current record's "facebook" value
 * @method string              getWeb1()          Returns the current record's "web1" value
 * @method integer             getRanking()       Returns the current record's "ranking" value
 * @method string              getDescripcion()   Returns the current record's "descripcion" value
 * @method boolean             getIsActive()      Returns the current record's "is_active" value
 * @method sfGuardUser         getUser()          Returns the current record's "User" value
 * @method Categoria           getCategoria()     Returns the current record's "Categoria" value
 * @method Doctrine_Collection getComentarios()   Returns the current record's "Comentarios" collection
 * @method Evento              setId()            Sets the current record's "id" value
 * @method Evento              setNombre()        Sets the current record's "nombre" value
 * @method Evento              setUserId()        Sets the current record's "user_id" value
 * @method Evento              setCategoriaId()   Sets the current record's "categoria_id" value
 * @method Evento              setFechaInicio()   Sets the current record's "fecha_inicio" value
 * @method Evento              setFechaTermino()  Sets the current record's "fecha_termino" value
 * @method Evento              setLugar()         Sets the current record's "lugar" value
 * @method Evento              setLogo()          Sets the current record's "logo" value
 * @method Evento              setTelefono()      Sets the current record's "telefono" value
 * @method Evento              setMail()          Sets the current record's "mail" value
 * @method Evento              setTwitter()       Sets the current record's "twitter" value
 * @method Evento              setFacebook()      Sets the current record's "facebook" value
 * @method Evento              setWeb1()          Sets the current record's "web1" value
 * @method Evento              setRanking()       Sets the current record's "ranking" value
 * @method Evento              setDescripcion()   Sets the current record's "descripcion" value
 * @method Evento              setIsActive()      Sets the current record's "is_active" value
 * @method Evento              setUser()          Sets the current record's "User" value
 * @method Evento              setCategoria()     Sets the current record's "Categoria" value
 * @method Evento              setComentarios()   Sets the current record's "Comentarios" collection
 * 
 * @package    scheedo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('evento');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             ));
        $this->hasColumn('nombre', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('categoria_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('fecha_inicio', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => 25,
             ));
        $this->hasColumn('fecha_termino', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => 25,
             ));
        $this->hasColumn('lugar', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('logo', 'blob', null, array(
             'type' => 'blob',
             ));
        $this->hasColumn('telefono', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('mail', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('twitter', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('facebook', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('web1', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('ranking', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('descripcion', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Categoria', array(
             'local' => 'categoria_id',
             'foreign' => 'id'));

        $this->hasMany('Comentario as Comentarios', array(
             'local' => 'id',
             'foreign' => 'evento_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}