<?php

/**
 * BaseCategoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property Evento $Categoria
 * 
 * @method integer   getId()        Returns the current record's "id" value
 * @method string    getNombre()    Returns the current record's "nombre" value
 * @method Evento    getCategoria() Returns the current record's "Categoria" value
 * @method Categoria setId()        Sets the current record's "id" value
 * @method Categoria setNombre()    Sets the current record's "nombre" value
 * @method Categoria setCategoria() Sets the current record's "Categoria" value
 * 
 * @package    scheedo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('categoria');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             ));
        $this->hasColumn('nombre', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Evento as Categoria', array(
             'local' => 'id',
             'foreign' => 'categoria_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}