<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/06/28 07:56:11

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=scheedo',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
