<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/06/28 07:56:11
$this->security = array (
  'user' => 
  array (
    'is_secure' => true,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
