ScheedoUser:
  actAs: { Timestampable: ~ }
  columns:
    scheedouser_id:  { type: integer, notnull: true, primary: true }
    first_name:      { type: string(255), notnull: true }
    last_name: { type: string(255), notnull: true }
    city: { type: string(255), notnull: true }
    birthday: {type: timestamp, notnull: true  }
    password: { type: string(255), notnull: true } 

ScheedoNormalUser:
  actAs: { Timestampable: ~ }
  columns:
    scheedonormaluser_id:  { type: integer, notnull: true, primary: true }
    facebook:      { type: string(255), notnull: false }
    twitter:      { type: string(255), notnull: false }
    flickr:      { type: string(255), notnull: false }
    scheedouser_id:  { type: integer, notnull: true }	
  relations:
    ScheedoUser: { onDelete: CASCADE, local: scheedouser_id, foreign: scheedouser_id, foreignAlias: ScheedoUser } 


ScheedoBusiness:
  actAs: { Timestampable: ~ }
  columns:
    scheedobusiness_id:  { type: integer, notnull: true, primary: true }
    facebook:      { type: string(255), notnull: false }
    twitter:      { type: string(255), notnull: false }
    flickr:      { type: string(255), notnull: false }   
    businessname:      { type: string(255), notnull: true }   
    ownershipvisibility:      { type: binary}   
    scheedouser_id:  { type: integer, notnull: true }	
  relations:
    ScheedoUser: { onDelete: CASCADE, local: scheedouser_id, foreign: scheedouser_id, foreignAlias: ScheedoUser }     	